In [113]:
import pandas as pd
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [114]:
test = pd.read_csv("/content/test.csv")
test

,Student_ID,Age,Gender,Degree,Branch,CGPA,Internships,Projects,Coding_Skills,Communication_Skills,Aptitude_Test_Score,Soft_Skills_Rating,Certifications,Backlogs,Placement_Status
0,15202,23,Male,B.Tech,Civil,7.32,2,4,5,6,56,6,1,0,Placed
1,4573,24,Female,MCA,ME,4.76,0,1,1,4,37,4,0,3,Not Placed
2,34424,20,Male,BCA,ME,6.16,0,3,3,8,68,6,1,3,Not Placed
3,38881,19,Male,B.Sc,IT,8.77,2,5,8,5,83,6,3,0,Placed
4,30191,23,Male,B.Tech,ME,7.63,0,3,4,6,66,7,1,0,Not Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,40640,19,Female,MCA,Civil,4.91,0,1,1,5,47,5,0,3,Not Placed
4996,46999,20,Male,B.Tech,ECE,6.82,2,3,5,7,76,6,2,0,Placed
4997,3816,20,Male,BCA,IT,5.80,0,3,6,7,56,6,2,2,Not Placed
4998,41368,23,Female,B.Tech,IT,7.67,1,4,7,6,67,4,2,0,Placed
4999,44562,24,Male,B.Tech,CSE,6.68,2,4,7,3,85,5,2,1,Not Placed

In [115]:
train = pd.read_csv("/content/train.csv")
train

,Student_ID,Age,Gender,Degree,Branch,CGPA,Internships,Projects,Coding_Skills,Communication_Skills,Aptitude_Test_Score,Soft_Skills_Rating,Certifications,Backlogs,Placement_Status
0,1048,22,Female,B.Tech,ECE,6.29,0,3,4,6,51,5,1,3,Not Placed
1,37820,20,Female,BCA,ECE,6.05,1,4,6,8,59,8,2,1,Not Placed
2,49668,22,Male,MCA,ME,7.22,1,4,6,6,58,6,2,2,Not Placed
3,19467,22,Male,MCA,ME,7.78,2,4,6,6,90,4,2,0,Placed
4,23094,20,Female,B.Tech,ME,7.63,1,4,6,5,79,6,2,0,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,9362,20,Male,MCA,Civil,7.84,2,5,9,7,68,6,3,1,Placed
44996,8940,19,Female,B.Sc,ME,8.28,1,4,6,5,74,5,2,0,Placed
44997,13097,20,Female,B.Sc,Civil,8.88,0,4,4,5,83,4,2,0,Not Placed
44998,12958,24,Female,MCA,ECE,5.90,1,3,6,6,60,2,2,1,Not Placed
44999,9565,23,Female,B.Tech,ME,6.28,0,4,6,6,64,7,2,3,Not Placed

In [116]:
train.describe()

,Student_ID,Age,CGPA,Internships,Projects,Coding_Skills,Communication_Skills,Aptitude_Test_Score,Soft_Skills_Rating,Certifications,Backlogs
count,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000
mean,24977.962600,20.999333,7.002290,0.774089,3.734222,5.691800,5.501644,69.385356,5.501644,1.800956,0.888133
std,14425.605704,1.995071,0.993855,0.844750,0.923738,1.994674,1.515374,13.909710,1.238722,0.650104,0.970954
min,1.000000,18.000000,4.500000,0.000000,1.000000,1.000000,1.000000,35.000000,1.000000,0.000000,0.000000
25%,12509.750000,19.000000,6.320000,0.000000,3.000000,4.000000,4.000000,60.000000,5.000000,1.000000,0.000000
50%,24957.500000,21.000000,7.000000,1.000000,4.000000,6.000000,6.000000,69.000000,5.000000,2.000000,1.000000
75%,37475.250000,23.000000,7.670000,1.000000,4.000000,7.000000,7.000000,79.000000,6.000000,2.000000,2.000000
max,50000.000000,24.000000,9.800000,3.000000,6.000000,10.000000,10.000000,100.000000,10.000000,3.000000,3.000000

In [117]:
test.describe()

,Student_ID,Age,CGPA,Internships,Projects,Coding_Skills,Communication_Skills,Aptitude_Test_Score,Soft_Skills_Rating,Certifications,Backlogs
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,25203.336600,21.006000,7.005410,0.770600,3.748800,5.720800,5.483800,69.523000,5.509800,1.807200,0.869800
std,14508.219611,1.994883,1.000486,0.852362,0.919928,1.987369,1.524796,13.879481,1.243307,0.648161,0.959704
min,12.000000,18.000000,4.500000,0.000000,1.000000,1.000000,1.000000,35.000000,1.000000,0.000000,0.000000
25%,12423.500000,19.000000,6.330000,0.000000,3.000000,4.000000,4.000000,60.000000,5.000000,1.000000,0.000000
50%,25468.500000,21.000000,7.010000,1.000000,4.000000,6.000000,5.000000,70.000000,6.000000,2.000000,1.000000
75%,37718.250000,23.000000,7.690000,1.000000,4.000000,7.000000,7.000000,79.000000,6.000000,2.000000,2.000000
max,49999.000000,24.000000,9.800000,3.000000,6.000000,10.000000,10.000000,100.000000,10.000000,3.000000,3.000000

In [118]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Student_ID            45000 non-null  int64
 1   Age                   45000 non-null  int64
 2   Gender                45000 non-null  object
 3   Degree                45000 non-null  object
 4   Branch                45000 non-null  object
 5   CGPA                  45000 non-null  float64
 6   Internships           45000 non-null  int64
 7   Projects              45000 non-null  int64
 8   Coding_Skills         45000 non-null  int64
 9   Communication_Skills  45000 non-null  int64
 10  Aptitude_Test_Score   45000 non-null  int64
 11  Soft_Skills_Rating    45000 non-null  int64
 12  Certifications        45000 non-null  int64
 13  Backlogs              45000 non-null  int64
 14  Placement_Status      45000 non-null  object
dtypes: float64(1), int64(10), object(4)
memory usage: 5.1+ MB

In [119]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Student_ID            5000 non-null   int64
 1   Age                   5000 non-null   int64
 2   Gender                5000 non-null   object
 3   Degree                5000 non-null   object
 4   Branch                5000 non-null   object
 5   CGPA                  5000 non-null   float64
 6   Internships           5000 non-null   int64
 7   Projects              5000 non-null   int64
 8   Coding_Skills         5000 non-null   int64
 9   Communication_Skills  5000 non-null   int64
 10  Aptitude_Test_Score   5000 non-null   int64
 11  Soft_Skills_Rating    5000 non-null   int64
 12  Certifications        5000 non-null   int64
 13  Backlogs              5000 non-null   int64
 14  Placement_Status      5000 non-null   object
dtypes: float64(1), int64(10), object(4)
memory usage: 586.1+ KB

In [120]:
train.isnull().sum()

Student_ID              0
Age                     0
Gender                  0
Degree                  0
Branch                  0
CGPA                    0
Internships             0
Projects                0
Coding_Skills           0
Communication_Skills    0
Aptitude_Test_Score     0
Soft_Skills_Rating      0
Certifications          0
Backlogs                0
Placement_Status        0
dtype: int64

In [121]:
test.isnull().sum()

Student_ID              0
Age                     0
Gender                  0
Degree                  0
Branch                  0
CGPA                    0
Internships             0
Projects                0
Coding_Skills           0
Communication_Skills    0
Aptitude_Test_Score     0
Soft_Skills_Rating      0
Certifications          0
Backlogs                0
Placement_Status        0
dtype: int64

In [122]:
t = train.drop("Student_ID", axis = 1)
t

,Age,Gender,Degree,Branch,CGPA,Internships,Projects,Coding_Skills,Communication_Skills,Aptitude_Test_Score,Soft_Skills_Rating,Certifications,Backlogs,Placement_Status
0,22,Female,B.Tech,ECE,6.29,0,3,4,6,51,5,1,3,Not Placed
1,20,Female,BCA,ECE,6.05,1,4,6,8,59,8,2,1,Not Placed
2,22,Male,MCA,ME,7.22,1,4,6,6,58,6,2,2,Not Placed
3,22,Male,MCA,ME,7.78,2,4,6,6,90,4,2,0,Placed
4,20,Female,B.Tech,ME,7.63,1,4,6,5,79,6,2,0,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,20,Male,MCA,Civil,7.84,2,5,9,7,68,6,3,1,Placed
44996,19,Female,B.Sc,ME,8.28,1,4,6,5,74,5,2,0,Placed
44997,20,Female,B.Sc,Civil,8.88,0,4,4,5,83,4,2,0,Not Placed
44998,24,Female,MCA,ECE,5.90,1,3,6,6,60,2,2,1,Not Placed
44999,23,Female,B.Tech,ME,6.28,0,4,6,6,64,7,2,3,Not Placed

In [123]:
x = train.drop("Placement_Status", axis = 1)
x

,Student_ID,Age,Gender,Degree,Branch,CGPA,Internships,Projects,Coding_Skills,Communication_Skills,Aptitude_Test_Score,Soft_Skills_Rating,Certifications,Backlogs
0,1048,22,Female,B.Tech,ECE,6.29,0,3,4,6,51,5,1,3
1,37820,20,Female,BCA,ECE,6.05,1,4,6,8,59,8,2,1
2,49668,22,Male,MCA,ME,7.22,1,4,6,6,58,6,2,2
3,19467,22,Male,MCA,ME,7.78,2,4,6,6,90,4,2,0
4,23094,20,Female,B.Tech,ME,7.63,1,4,6,5,79,6,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,9362,20,Male,MCA,Civil,7.84,2,5,9,7,68,6,3,1
44996,8940,19,Female,B.Sc,ME,8.28,1,4,6,5,74,5,2,0
44997,13097,20,Female,B.Sc,Civil,8.88,0,4,4,5,83,4,2,0
44998,12958,24,Female,MCA,ECE,5.90,1,3,6,6,60,2,2,1
44999,9565,23,Female,B.Tech,ME,6.28,0,4,6,6,64,7,2,3

In [124]:
y = train.Placement_Status
y

0        Not Placed
1        Not Placed
2        Not Placed
3            Placed
4            Placed
            ...
44995        Placed
44996        Placed
44997    Not Placed
44998    Not Placed
44999    Not Placed
Name: Placement_Status, Length: 45000, dtype: object

In [125]:
num_col = x.select_dtypes(include = "number").columns
obj_col = x.select_dtypes(include = "object").columns
obj_col
num_col

Index(['Student_ID', 'Age', 'CGPA', 'Internships', 'Projects', 'Coding_Skills',
       'Communication_Skills', 'Aptitude_Test_Score', 'Soft_Skills_Rating',
       'Certifications', 'Backlogs'],
      dtype='object')

In [126]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [127]:
#preprocessing Pipeline
Preprocessor = ColumnTransformer([("Scaler", StandardScaler(),num_col), ("encoder", OneHotEncoder(),obj_col)])
Preprocessor

ColumnTransformer(transformers=[('Scaler', StandardScaler(),
                                 Index(['Student_ID', 'Age', 'CGPA', 'Internships', 'Projects', 'Coding_Skills',
       'Communication_Skills', 'Aptitude_Test_Score', 'Soft_Skills_Rating',
       'Certifications', 'Backlogs'],
      dtype='object')),
                                ('encoder', OneHotEncoder(),
                                 Index(['Gender', 'Degree', 'Branch'], dtype='object'))])

In [128]:
#pipeline
Pipeline = Pipeline([("Preprocessor", Preprocessor), ("svc", SVC())])
Pipeline

Pipeline(steps=[('Preprocessor',
                 ColumnTransformer(transformers=[('Scaler', StandardScaler(),
                                                  Index(['Student_ID', 'Age', 'CGPA', 'Internships', 'Projects', 'Coding_Skills',
       'Communication_Skills', 'Aptitude_Test_Score', 'Soft_Skills_Rating',
       'Certifications', 'Backlogs'],
      dtype='object')),
                                                 ('encoder', OneHotEncoder(),
                                                  Index(['Gender', 'Degree', 'Branch'], dtype='object'))])),
                ('svc', SVC())])

In [129]:
Pipeline.fit(x, y)

Pipeline(steps=[('Preprocessor',
                 ColumnTransformer(transformers=[('Scaler', StandardScaler(),
                                                  Index(['Student_ID', 'Age', 'CGPA', 'Internships', 'Projects', 'Coding_Skills',
       'Communication_Skills', 'Aptitude_Test_Score', 'Soft_Skills_Rating',
       'Certifications', 'Backlogs'],
      dtype='object')),
                                                 ('encoder', OneHotEncoder(),
                                                  Index(['Gender', 'Degree', 'Branch'], dtype='object'))])),
                ('svc', SVC())])

In [130]:
ytest = test.Placement_Status
test = test.drop(["Student_ID", "Placement_Status"], axis = 1)

In [131]:
ypred = Pipeline_clean.predict(test)
ypred

array(['Placed', 'Not Placed', 'Not Placed', ..., 'Not Placed', 'Placed',
       'Not Placed'], dtype=object)

In [132]:
confusion_matrix(ytest, ypred)

array([[3140,   48],
       [  37, 1775]])

In [133]:
print(classification_report(ytest, ypred))
print("Training eff:", Pipeline_clean.score(x,y))
print("Testing eff:", Pipeline_clean.score(test, ytest))

              precision    recall  f1-score   support

  Not Placed       0.99      0.98      0.99      3188
      Placed       0.97      0.98      0.98      1812

    accuracy                           0.98      5000
   macro avg       0.98      0.98      0.98      5000
weighted avg       0.98      0.98      0.98      5000

Training eff: 0.9892888888888889
Testing eff: 0.983

In [134]:
new_data = test.sample()
print(new_data)

    Age Gender Degree Branch  CGPA  Internships  Projects  Coding_Skills  \
99   19   Male    MCA     ME  6.83            1         4              6

    Communication_Skills  Aptitude_Test_Score  Soft_Skills_Rating  \
99                     5                   60                   8

    Certifications  Backlogs
99               2         2

In [135]:
Pipeline_clean.predict(new_data)[0]

'Not Placed'